### ISSUE TITLE
could I run this code

### ISSUE THREAD

**Issue by hxtruong6** [waltergerych/RBCC#3]
I see some errors in **classifiers.py** which is a lack of libraries.
How could code run with a lack of libraries `numpy` and `copy`?
The original code doesn't contain two of these libraries.
![image](https://user-images.githubusercontent.com/24609363/224625243-a0f8b0f0-284a-46b4-bc8c-607d36da3c31.png)

**Comment by waltergerych** [comment]
The function in the classifiers script were initially in the models file (where numpy and copy are imported). These imports were left out of the script when I split them into a separate .py file. Thank you for raising the issue
